@echo off
echo Starting Node.js Orchestrator...
start cmd /k "cd orchestrator && npm run dev"

echo Starting Python Worker...
start cmd /k ".\.venv\Scripts\python.exe -m uvicorn app.worker_main:app --port 8000"
